I'm sorry, but an uncaught exception occurred.

While parsing C:\Users\Aphrodite\Desktop\Dropbox\CECS343_VisualNovel/game/script.rpy.
ScriptError: Name (u'/home/tom/ab/renpy/template/game/script.rpy', 1341714480, 1) is defined twice: at game/script.rpy:10 and game/script.rpy:10.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Aphrodite\Desktop\renpy-6.17.7-sdk\renpy\bootstrap.py", line 285, in bootstrap
    renpy.main.main()
  File "C:\Users\Aphrodite\Desktop\renpy-6.17.7-sdk\renpy\main.py", line 248, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Users\Aphrodite\Desktop\renpy-6.17.7-sdk\renpy\script.py", line 177, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Aphrodite\Desktop\renpy-6.17.7-sdk\renpy\script.py", line 447, in load_appropriate_file
    if not self.load_file(dir, fn + compiled, initcode):
  File "C:\Users\Aphrodite\Desktop\renpy-6.17.7-sdk\renpy\script.py", line 320, in load_file
    self.finish_load(stmts, initcode)
  File "C:\Users\Aphrodite\Desktop\renpy-6.17.7-sdk\renpy\script.py", line 392, in finish_load
    node.filename, node.linenumber))
ScriptError: Name (u'/home/tom/ab/renpy/template/game/script.rpy', 1341714480, 1) is defined twice: at game/script.rpy:10 and game/script.rpy:10.

Windows-7-6.1.7601-SP1
Ren'Py 6.17.7.521
 
